export const ADD_POSTMAN_SUCCESS = 'ADD_POSTMAN_SUCCESS';
export const ADD_POSTMAN_FAIL = 'ADD_POSTMAN_FAIL';

export const EDIT_POSTMAN_SUCCESS = 'EDIT_POSTMAN_SUCCESS';
export const EDIT_POSTMAN_FAIL = 'EDIT_POSTMAN_FAIL';

export const REMOVE_POSTMAN_SUCCESS = 'REMOVE_POSTMAN_SUCCESS';
export const REMOVE_POSTMAN_FAIL = 'REMOVE_POSTMAN_FAIL';