# Generated by Django 4.1 on 2022-09-27 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('role', models.CharField(choices=[('GUEST', 'Гость'), ('SUBSCRIBER', 'Подписчик'), ('POSTMAN', 'Почтальон'), ('OPERATOR', 'Оператор'), ('MANAGER', 'Заведующий'), ('ADMIN', 'Админ')], default='SUBSCRIBER', max_length=50, verbose_name='Роль')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Подленность')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('address', models.ForeignKey(blank=True, default='51', null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Адрес')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user_accounts',
            },
        ),
    ]
