export const ADD_SUBSCRIBER_SUCCESS = 'ADD_SUBSCRIBER_SUCCESS';
export const ADD_SUBSCRIBER_FAIL = 'ADD_SUBSCRIBER_FAIL';

export const EDIT_SUBSCRIBER_SUCCESS = 'EDIT_SUBSCRIBER_SUCCESS';
export const EDIT_SUBSCRIBER_FAIL = 'EDIT_SUBSCRIBER_FAIL';

export const DELETE_SUBSCRIBER_SUCCESS = 'DELETE_SUBSCRIBER_SUCCESS';
export const DELETE_SUBSCRIBER_FAIL = 'DELETE_SUBSCRIBER_FAIL';