export const ADD_STREET_SUCCESS = 'ADD_STREET_SUCCESS';
export const ADD_STREET_FAIL = 'ADD_STREET_FAIL';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL';
export const ADD_POI_SUCCESS = 'ADD_POI_SUCCESS';
export const ADD_POI_FAIL = 'ADD_POI_FAIL';


export const EDIT_STREET_SUCCESS = 'EDIT_STREET_SUCCESS';
export const EDIT_STREET_FAIL = 'EDIT_STREET_FAIL';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const EDIT_ADDRESS_FAIL = 'EDIT_ADDRESS_FAIL';
export const EDIT_POI_SUCCESS = 'EDIT_POI_SUCCESS';
export const EDIT_POI_FAIL = 'EDIT_POI_FAIL';


export const DELETE_STREET_SUCCESS = 'DELETE_STREET_SUCCESS';
export const DELETE_STREET_FAIL = 'DELETE_STREET_FAIL';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL';
export const DELETE_POI_SUCCESS = 'DELETE_POI_SUCCESS';
export const DELETE_POI_FAIL = 'DELETE_POI_FAIL';