export const ADD_DELIVERY_SUCCESS = 'ADD_DELIVERY_SUCCESS';
export const ADD_DELIVERY_FAIL = 'ADD_DELIVERY_FAIL';

export const EDIT_DELIVERY_SUCCESS = 'EDIT_DELIVERY_SUCCESS';
export const EDIT_DELIVERY_FAIL = 'EDIT_DELIVERY_FAIL';

export const DELETE_DELIVERY_SUCCESS = 'DELETE_DELIVERY_SUCCESS';
export const DELETE_DELIVERY_FAIL = 'DELETE_DELIVERY_FAIL';