# Generated by Django 4.1 on 2022-09-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('flat', models.CharField(max_length=10, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_street', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип улицы')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Улицу',
                'verbose_name_plural': 'Улицы',
                'db_table': 'street',
            },
        ),
        migrations.CreateModel(
            name='PostOfficeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название компании')),
                ('manager_info', models.CharField(max_length=200, verbose_name='О упровляющем')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Адрес компании')),
            ],
            options={
                'verbose_name': 'О почтовом отделении',
                'verbose_name_plural': 'О почтовых отделениях',
                'db_table': 'post_office_info',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.street', verbose_name='Улица'),
        ),
    ]
