# Generated by Django 4.1 on 2022-09-27 15:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import editions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=45, verbose_name='Тип издания')),
            ],
            options={
                'verbose_name': 'Тип издания',
                'verbose_name_plural': 'Типы изданий',
                'db_table': 'edition_type',
                'unique_together': {('type_name',)},
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to=editions.models.upload_to, verbose_name='Обложка')),
                ('index', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Индекс')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('price', models.FloatField(blank=True, max_length=10, null=True, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('edition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.editiontype', verbose_name='Тип издания')),
            ],
            options={
                'verbose_name': 'Издание',
                'verbose_name_plural': 'Издания',
                'db_table': 'edition',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_subscription', models.DateField(default=datetime.date.today, verbose_name='Дата начала подписки')),
                ('duration', models.IntegerField(default=1, verbose_name='Продолжительность')),
                ('is_subscription', models.BooleanField(default=True, verbose_name='Подписка')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='editions.edition', verbose_name='Издание')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписку',
                'verbose_name_plural': 'Подписки',
                'db_table': 'subscription',
                'unique_together': {('subscriber', 'edition')},
            },
        ),
    ]
