export const EDITIONS_LOADED_SUCCESS = 'EDITIONS_LOADED_SUCCESS';
export const EDITIONS_LOADED_FAIL = 'EDITIONS_LOADED_FAIL';
export const SUBSCRIBE_EDITION_LOADED_SUCCESS = 'SUBSCRIBE_EDITION_LOADED_SUCCESS';
export const SUBSCRIBE_EDITION_LOADED_FAIL = 'SUBSCRIBE_EDITION_LOADED_FAIL';
export const UN_SUBSCRIBE_EDITION_LOADED_SUCCESS = 'UN_SUBSCRIBE_EDITION_LOADED_SUCCESS';
export const UN_SUBSCRIBE_EDITION_LOADED_FAIL = 'UN_SUBSCRIBE_EDITION_LOADED_FAIL';
export const EDITION_TYPES_LOADED_SUCCESS = 'EDITION_TYPES_LOADED_SUCCESS';
export const EDITION_TYPES_LOADED_FAIL = 'EDITION_TYPES_LOADED_FAIL';

export const ADD_EDITION_SUCCESS = 'ADD_EDITION_SUCCESS';
export const ADD_EDITION_FAIL = 'ADD_EDITION_FAIL';
export const ADD_EDITION_TYPE_SUCCESS = 'ADD_EDITION_TYPE_SUCCESS';
export const ADD_EDITION_TYPE_FAIL = 'ADD_EDITION_TYPE_FAIL';
export const ADD_SUBSCRIPTION_SUCCESS = 'ADD_SUBSCRIPTION_SUCCESS';
export const ADD_SUBSCRIPTION_FAIL = 'ADD_SUBSCRIPTION_FAIL';


export const EDIT_EDITION_SUCCESS = 'EDIT_EDITION_SUCCESS';
export const EDIT_EDITION_FAIL = 'EDIT_EDITION_FAIL';
export const EDIT_EDITION_TYPE_SUCCESS = 'EDIT_EDITION_TYPE_SUCCESS';
export const EDIT_EDITION_TYPE_FAIL = 'EDIT_EDITION_TYPE_FAIL';
export const EDIT_SUBSCRIPTION_SUCCESS = 'EDIT_SUBSCRIPTION_SUCCESS';
export const EDIT_SUBSCRIPTION_FAIL = 'EDIT_SUBSCRIPTION_FAIL';

export const REMOVE_EDITION_SUCCESS = 'REMOVE_EDITION_SUCCESS';
export const REMOVE_EDITION_FAIL = 'REMOVE_EDITION_FAIL';
export const REMOVE_EDITION_TYPE_SUCCESS = 'REMOVE_EDITION_TYPE_SUCCESS';
export const REMOVE_EDITION_TYPE_FAIL = 'REMOVE_EDITION_TYPE_FAIL';
export const REMOVE_SUBSCRIPTION_SUCCESS = 'REMOVE_SUBSCRIPTION_SUCCESS';
export const REMOVE_SUBSCRIPTION_FAIL = 'REMOVE_SUBSCRIPTION_FAIL';




