export const ADD_DISTRICT_SUCCESS = 'ADD_DISTRICT_SUCCESS';
export const ADD_DISTRICT_FAIL = 'ADD_DISTRICT_FAIL';
export const ADD_DISTRICT_STREET_SUCCESS = 'ADD_DISTRICT_STREET_SUCCESS';
export const ADD_DISTRICT_STREET_FAIL = 'ADD_DISTRICT_STREET_FAIL';

export const EDIT_DISTRICT_SUCCESS = 'EDIT_DISTRICT_SUCCESS';
export const EDIT_DISTRICT_FAIL = 'EDIT_DISTRICT_FAIL';
export const EDIT_DISTRICT_STREET_SUCCESS = 'EDIT_DISTRICT_STREET_SUCCESS';
export const EDIT_DISTRICT_STREET_FAIL = 'EDIT_DISTRICT_STREET_FAIL';

export const DELETE_DISTRICT_SUCCESS = 'DELETE_DISTRICT_SUCCESS';
export const DELETE_DISTRICT_FAIL = 'DELETE_DISTRICT_FAIL';
export const DELETE_DISTRICT_STREET_SUCCESS = 'DELETE_DISTRICT_STREET_SUCCESS';
export const DELETE_DISTRICT_STREET_FAIL = 'DELETE_DISTRICT_STREET_FAIL';